image: node:6.10
stages: 
  - install
  - build
  # - deploy

cache: 
  paths:
    - node_modules/

install: 
  stage: install
  script: 
    - npm install
    - echo "install success"
  only:
    - dev

build:
  stage: build
  script: 
    - npm run build
    - echo "build success"
  only:
    - dev
